#系统配置
[system]
#启动地址
address = "9001"
#是否开启跨域
cors = true
#是否开发调试模式
debug = true
#项目名称
app_name = "antgo"

#接口请求日志
[log]
#路径
path = "./log/app.log"
#输出格式 支持(json、console)
format = "json"
#日志服务名称
service_name = "admin"
#日志输出等级 all、info、warn、error、debug、dpanic、panic、fatal
level = "all"
#是否输出控制台
console = true
#是否开启日志
switch = true
#文件最长保存时间(天)
max_age = 180
#分割大小(MB)
max_size = 10
#保留30个备份(个)
max_backups = 2000
#是否需要压缩
compress = false
#header 白名单
header_whitelist = ["Device-Id", "Authorization", "Accept", "Accept-Language", "Origin", "Referer", "User-Agent"]

#数据库设置
[[connections]]
#数据库名称(必须唯一)
name = "mysql"
#数据库类型支持mysql、pgsql、sqlsrv、clickhouse
type = "mysql"
#服务器地址
hostname = "127.0.0.1"
#服务器端口
port = "3306"
#数据库用户名
username = "root"
#数据库密码
password = "root"
#数据库名
database = "antgo"
#数据库连接参数
params = "charset=utf8mb4&parseTime=True&loc=Local"
#是否开启日志
log = true
#设置空闲连接池中的最大连接数
max_idle_conns = 100
#设置数据库的最大打开连接数。
max_open_conns = 200
#设置连接可能被重用的最大时间(秒)。
conn_max_lifetime = 300
#设置连接最大生命周期(小时)。
conn_max_idleTime = 2
#日志等级,1=静默;2=错误;3=警告;4=信息
level = 4

#Redis配置
[[redis]]
name = ""
address = ""
password = ""
db = 0

#邮箱
[email]
switch = true
to = ['']
from = ''
host = ''
secret = ''

#图片验证码
[captcha]
#验证码长度
length = 4
#验证码宽度
width = 240
#验证码高度
height = 80

#Json web token
[jwt]
#过期时间(小时)
exp = 168
#私钥
private_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAtKaIYSS59GF8vxJooI1THCFR6Q6bzcEf2LnQHdkuWd0oVGf5
JAsbPiNtQ45+AhKRfIfmoSWUzSl2lBZ64TGIL+jhX2bUy3N3R20weT0roNEGW9pA
/uf7YDYFgIed2fQpwQ8MfvtPWsiIZpOnc1OE8TYeZZLbkb93rVyles/WjhYtMCGH
pKrI21IbknKqMJkFfb3gi0mQidqy1lvd6OIfaXacbfkuoJmANA/KFQ5Ywii6RX4W
zoJunW410bbm8tEpR17XKymEoFzuo8+QWfjqoVhD4lmIW0gww9hXhA8/U6fiaUwL
J586MDuNzQImnxaJ/WuUPNzlOfaSKUW06DASlQIDAQABAoIBAGZu23wB4DNTJ/IM
FSmcmRilSBXXg776l/1C92BFasPn5FtgDWRDq/HjEqyw2oCAWOB9CugrMCHZNfSo
foq8lFVePpTi8Rxf362vm0HTzq5Ed8+ThTFFB0O5vgrwWzBgA2EGEHbcN1XpyXYo
mVWKcSJ5JmlACaKuJ8U0eFyYBzfPJXLqF4rIALBSbDE4MQGZEz85/U0Mf7zMU7Ks
JjX8661xlufnKDLlCRxNQh9Uarf9R4//LFtdLrFy2CkvrjArzfX50k3MORSjJEJt
GTX8nXiEGTpnNL8UfaUPekXwM0Ua/4j+EVOslruWYg5YuJHbIWSHaTgr4rb/BF5Y
Ip7RaCECgYEA2MsPBVeu1Y8aAttNecWnQLf8zxmaKj2Ozms1md24wWEUTnQFfILT
Br9igghjI3MbF08ERAmD75lstl11/KNzHqSk3HhOJMkY7rUQ8M6ytsmMvrsfea41
qCKtLwISfZ6dFMHgBMPQJDgaB6AOmrfQ7V63C+pPTd9VouLkkRHsGb0CgYEA1VIq
UiefJzCdRx1qdnkNaj/ryiu6tLExA9wUujOpKNV1h3tcPBn6VZi0GTwtmEzUAbtp
ciQ5IKdIq5Pcc4SjvG8THsreP3a8eWpJ2Cgi+6trXbQk3axMmHorYFqCq10/ZyPD
Y2m9qvLFQ1H843N1A01Oix9Mcz4066DQY8fMbbkCgYAHTB5/UYpDCgQYIIWlGbAd
j5Pk7Lmxvky2SgmN2lbDu57RXTpqDIVJ7ttEAUBFCzTYPgKov6E/SWzNXqwACwhu
+Z/LBAmtV0+NiW6+jFabrIEeUnImyGRp+nDV6j3xGIu1DSmbP3QcI/9MTmjvcEyK
EOwcbJCq0F+zkeubrnzCCQKBgHDLYl9QXgId3XvF3Q5J0cMVi3q6Bp4WdyFgVIFk
YZSa0etSWiHZZpmuBcS2IjG+pfdIfmgBKUfPzEgVBeL7BozTepu0jzGleeEFR4iJ
KH5EVKAWacvgmBujtZ3cHe24f5bsvRqqxcRHW/DNwFcQLJYTYW2EnirtgJP601V/
RuPZAoGBALfKZEKMJS7wqOnw2oqOQCHSaXniTjh+0WeSASiSYI8xZC9JsXbVfNfG
yLPW8BvM3iblkV6h2wlTBlwCJNjCtg8OKUzoPzDi4qkOgAYLgbYgcxhkkFBttrLG
Fcxq3Tjr5U5RP2huHBmBfmfVpOALTwzsKXyVZd2VRPeljM0IaFPA
-----END RSA PRIVATE KEY-----
"""
#公钥
public_key = """-----BEGIN RSA PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKaIYSS59GF8vxJooI1T
HCFR6Q6bzcEf2LnQHdkuWd0oVGf5JAsbPiNtQ45+AhKRfIfmoSWUzSl2lBZ64TGI
L+jhX2bUy3N3R20weT0roNEGW9pA/uf7YDYFgIed2fQpwQ8MfvtPWsiIZpOnc1OE
8TYeZZLbkb93rVyles/WjhYtMCGHpKrI21IbknKqMJkFfb3gi0mQidqy1lvd6OIf
aXacbfkuoJmANA/KFQ5Ywii6RX4WzoJunW410bbm8tEpR17XKymEoFzuo8+QWfjq
oVhD4lmIW0gww9hXhA8/U6fiaUwLJ586MDuNzQImnxaJ/WuUPNzlOfaSKUW06DAS
lQIDAQAB
-----END RSA PUBLIC KEY-----
"""
