package vo

// 请求参数无效
const INVALID_REQUEST_PARAMETERS = "INVALID_REQUEST_PARAMETERS"

// 操作成功
const SUCCESS = "SUCCESS"

// 操作失败
const FAILED = "FAILED"

// 创建操作状态
const (
	CREATION_FAILED  = "CREATION_FAILED"
	CREATION_SUCCESS = "CREATION_SUCCESS"
)

// 更新操作状态
const (
	UPDATE_FAILED  = "UPDATE_FAILED"
	UPDATE_SUCCESS = "UPDATE_SUCCESS"
)

// 删除操作状态
const (
	DELETE_FAILED  = "DELETE_FAILED"
	DELETE_SUCCESS = "DELETE_SUCCESS"
)

// 登录相关
const (
	LOGIN_ERROR   = "LOGIN_ERROR"
	LOGIN_SUCCESS = "LOGIN_SUCCESS"
)

// 验证码错误
const CAPTCHA_ERROR = "CAPTCHA_ERROR"

// 认证相关
const (
	AUTH_ERROR        = "AUTH_ERROR"
	AUTH_DEVICE_ERROR = "AUTH_DEVICE_ERROR"
	AUTH_USER_ERROR   = "AUTH_USER_ERROR"
)
