package vo

// INVALID_REQUEST_PARAMETERS 无效的请求参数
const INVALID_REQUEST_PARAMETERS = "INVALID_REQUEST_PARAMETERS"

// SUCCESS 成功
const SUCCESS = "SUCCESS"

// FAILED 失败
const FAILED = "FAILED"

// CREATION_FAILED 创建失败
const CREATION_FAILED = "CREATION_FAILED"

// CREATION_SUCCESS 创建成功
const CREATION_SUCCESS = "CREATION_SUCCESS"

// UPDATE_FAILED 更新失败
const UPDATE_FAILED = "UPDATE_FAILED"

// UPDATE_SUCCESS 更新成功
const UPDATE_SUCCESS = "UPDATE_SUCCESS"

// DELETE_FAILED 删除失败
const DELETE_FAILED = "DELETE_FAILED"

// DELETE_SUCCESS 删除成功
const DELETE_SUCCESS = "DELETE_SUCCESS"

// CAPTCHA_ERROR 验证码错误
const CAPTCHA_ERROR = "CAPTCHA_ERROR"

// LOGIN_ERROR 登录错误
const LOGIN_ERROR = "LOGIN_ERROR"

// LOGIN_SUCCESS 登录成功
const LOGIN_SUCCESS = "LOGIN_SUCCESS"

// AUTH_ERROR 认证错误
const AUTH_ERROR = "AUTH_ERROR"

// AUTH_USER_ERROR 用户不存在
const AUTH_USER_ERROR = "AUTH_USER_ERROR"
